In [3]:
# importing the libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

C:\Users\BKP\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\BKP\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\BKP\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\BKP\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type

In [5]:
# importing the dataset

dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [6]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [7]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

In [8]:
# splitting the dataset into the training set and test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [9]:
X_train.shape

(7654, 4)

In [10]:
X_test.shape

(1914, 4)

In [11]:
y_test.shape

(1914,)

In [12]:
y_train.shape

(7654,)

In [13]:
# Building the ANN

In [15]:
# initializing the ANN

ann = tf.keras.models.Sequential()

In [16]:
# adding the input layer and first hidden layer

ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

In [17]:
# adding the second hidden layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [18]:
# adding the output layer

ann.add(tf.keras.layers.Dense(units=1))

In [19]:
# Training the ANN

In [20]:
# compiling the ANN

ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

Instructions for updating:
Colocations handled automatically by placer.


In [21]:
# Training the ANN model on the training set

ann.fit(X_train, y_train, batch_size = 32, epochs=100)

Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Use tf.cast instead.
Epoch 1/100
7654/7654 [==============================] - 3s 368us/sample - loss: 31103.1514
Epoch 2/100
7654/7654 [==============================] - 0s 60us/sample - loss: 211.8708
Epoch 3/100
7654/7654 [==============================] - 0s 50us/sample - loss: 205.2123
Epoch 4/100
7654/7654 [==============================] - 0s 58us/sample - loss: 197.1475
Epoch 5/100
7654/7654 [==============================] - 0s 55us/sample - loss: 187.8746
Epoch 6/100
7654/7654 [==============================] - 0s 51us/sample - loss: 177.2984
Epoch 7/100
7654/7654 [==============================] - 0s 65us/sample - loss: 165.6643
Epoch 8/100
7654/7654 [==============================] - 0s 53us/sample - loss: 153.6103
Epoch 9/100
7654/7654 [==============================] - 0s 58us/sample - loss: 140.7246
Epoch 10/100
7654/7654 [==============================] - 1s 69us/sample - loss: 127.7782
Epoch 11/1

In [22]:
# predicting the result on the test set

ann.predict(X_test)

array([[432.72037],
       [463.8556 ],
       [467.37817],
       ...,
       [474.5833 ],
       [441.38303],
       [460.58725]], dtype=float32)

In [23]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[432.72 431.23]
 [463.86 460.01]
 [467.38 461.14]
 ...
 [474.58 473.26]
 [441.38 438.  ]
 [460.59 463.28]]
